version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(â¬†ï¸deps):'
      prefix-development: 'chore(â¬†ï¸ğŸ”¨dev-deps):'
    assignees:
      - "shanpriyan"
    open-pull-requests-limit: 2
    rebase-strategy: auto
